from .base_options import BaseOptions


class TrainOptions(BaseOptions):
    def initialize(self):
        BaseOptions.initialize(self)
        self.parser.add_argument('--lambda_sharp', type=float, default=50.0, help='weight for full-image Sobel sharpness loss (v4a+ models)')
        self.parser.add_argument('--lambda_ffl', type=float, default=300.0, help='weight for focal frequency loss')
        self.parser.add_argument('--lambda_sharp_cloud', type=float, default=200.0, help='weight for att_A-weighted Sobel loss')
        self.parser.add_argument('--lambda_gB_cloud', type=float, default=10.0, help='weight for direct g_B cloud supervision loss')
        self.parser.add_argument('--lambda_ffl_g2', type=float, default=150.0, help='v4c_ffl_sar: FFL weight on fake_C (G2 output) vs real_B')
        self.parser.add_argument('--lambda_sar_reliance', type=float, default=20.0, help='v4c_ffl_sar: att_A-weighted |g_B - fake_C.detach()|, pulls netG toward the SAR-derived translation in cloud regions')
        self.parser.add_argument('--display_freq', type=int, default=100, help='frequency of showing training results on screen')
        self.parser.add_argument('--print_freq', type=int, default=100, help='frequency of showing training results on console')
        self.parser.add_argument('--save_latest_freq', type=int, default=5000, help='frequency of saving the latest results')
        self.parser.add_argument('--save_epoch_freq', type=int, default=5, help='frequency of saving checkpoints at the end of epochs')
        self.parser.add_argument('--continue_train', action='store_true', help='continue training: load the latest model')
        self.parser.add_argument('--epoch_count', type=int, default=1, help='the starting epoch count, we save the model by <epoch_count>, <epoch_count>+<save_latest_freq>, ...')
        self.parser.add_argument('--phase', type=str, default='train', help='train, val, test, etc')
        self.parser.add_argument('--which_epoch', type=str, default='latest', help='which epoch to load? set to latest to use latest cached model')
        self.parser.add_argument('--niter', type=int, default=100, help='# of iter at starting learning rate')
        self.parser.add_argument('--niter_decay', type=int, default=100, help='# of iter to linearly decay learning rate to zero')
        self.parser.add_argument('--beta1', type=float, default=0.5, help='momentum term of adam')
        self.parser.add_argument('--lr', type=float, default=0.0002, help='initial learning rate for adam')
        self.parser.add_argument('--no_lsgan', action='store_true', help='do *not* use least square GAN, if false, use vanilla GAN')
        self.parser.add_argument('--lambda_A', type=float, default=10.0, help='weight for cycle loss (A -> B -> A)')
        self.parser.add_argument('--lambda_B', type=float, default=10.0, help='weight for cycle loss (B -> A -> B)')
        self.parser.add_argument('--loss_attn_A', type=float, default=1.0, help='weight for attention sparse loss for A')
        self.parser.add_argument('--lambda_clear', type=float, default=0.1, help='v4a/v4b: clear-pixel weight fraction in attention-weighted L1 (cloud pixels get weight 1.0, clear pixels get this fraction)')
        self.parser.add_argument('--frozen_attn_name', type=str, default='sen12mscr_nir_teacher_v3', help='v4a/v4b: checkpoint experiment name to load frozen netA from')
        self.parser.add_argument('--frozen_attn_epoch', type=str, default='latest', help='v4a/v4b: epoch tag for the frozen netA checkpoint')
        self.parser.add_argument('--pretrained_G_name', type=str, default='sen12mscr_nir_teacher_v3', help='v4b: checkpoint experiment name to warm-start netG from (fresh run only)')
        self.parser.add_argument('--pretrained_G_epoch', type=str, default='latest', help='v4b: epoch tag for the pretrained netG checkpoint')
        self.parser.add_argument('--warmstart_name', type=str, default='sen12mscr_nir_teacher_v4a', help='v4c/v4adv: experiment to warm-start G/G2/D from on a fresh (non-continue_train) run')
        self.parser.add_argument('--warmstart_epoch', type=str, default='latest', help='v4c/v4adv: epoch tag for the warm-start checkpoint')
        self.parser.add_argument('--freeze_netA', action='store_true', help='freeze netA weights (use as fixed cloud-mask oracle, no gradient into netA)')
        self.parser.add_argument('--loss_attn_B', type=float, default=1.0, help='weight for attention sparse loss for B')
        self.parser.add_argument('--attn_cycle_weight', type=float, default=1.0, help='weight for attention cycle-consistent loss')
        self.parser.add_argument('--pool_size', type=int, default=50, help='the size of image buffer that stores previously generated images')
        self.parser.add_argument('--no_html', action='store_true', help='do not save intermediate training results to [opt.checkpoints_dir]/[opt.name]/web/')
        self.parser.add_argument('--lr_policy', type=str, default='lambda', help='learning rate policy: lambda|step|plateau')
        self.parser.add_argument('--lr_decay_iters', type=int, default=100, help='multiply by a gamma every lr_decay_iters iterations')
        self.parser.add_argument('--identity', type=float, default=0.0, help='use identity mapping. Setting identity other than 1 has an effect of scaling the weight of the identity mapping loss. For example, if the weight of the identity loss should be 10 times smaller than the weight of the reconstruction loss, please set optidentity = 0.1')
        self.isTrain = True
